baseurl:
url: https://xpmoae.github.io
title: 顾星辰
subtitle: "The sandglass remembers the time we mislay"
description: "moae's personal page"
date_format: "ordinal"
# timezone: Asia/Guangzhou
encoding: "utf-8"
side_bar_repo_limit: 5

author: moae
organization: UESTC
organization_url: http://www.uestc.edu.cn
github_username: xpmoae
location: Guangzhou, China
email: 1124034062@qq.com

# Navigation
navs:
  -
    href: /
    label: Homepage

  -
    href: /cv/
    label: CV

  -
    href: /publications/
    label: Publications

  -
    href: /categories/
    label: Blogs

  -
    href: /wiki/
    label: Wiki

  # -
  #   href: /links/
  #   label: Links

# RSS
subscribe_rss: /feed.xml

# Jekyll
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: xpmoae/xpmoae.github.io

# Search
simple_jekyll_search:
    fulltext: false # full text search enable
    limit: 10 # limitation of the search results to show

# Analytics
google:
    analytics_id: UA-80669434-1
github: [metadata]
